mongo3:
  hostname: mongo3
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
#  restart: always

mongo2:
  hostname: mongo2
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
#  restart: always

mongo1:
  hostname: mongo1
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
#  restart: always

mongosetup:
  image: mongo:3.2
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

java:
  build: java/
  container_name: java

aempub:
  hostname: aempub
  build: aem/
  dockerfile: Dockerfile-pub
  ports:
    - "4503:4503"
  command:
     ["java", "-XX:MaxPermSize=512M", "-Xmx1524M", "-Xms512M", "-jar", "cq-quickstart-6.1.0.jar", "-p", "4503", "-r", "publish"]
 #  restart: always

aemaut:
 hostname: aemaut
 build: aem/
 ports:
   - "4502:4502"
 links:
   - mongo1:mongo1
   - mongo2:mongo2
   - aempub:aempub
 command:
    ["java", "-XX:MaxPermSize=512M", "-Xmx1524M", "-Xms512M", "-mx4g", "-jar", "cq-quickstart-6.1.0.jar", "-p", "4502", "-r", "author,crx3,crx3mongo", "-Doak.mongo.uri=mongodb://mongo1:27017,mongo2:27017"]
#  restart: always
