mongo3:
  hostname: mongo3
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27018:27017"
    - "28018:28017"
#  restart: always

mongo2:
  hostname: mongo2
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27019:27017"
    - "28019:28017"
#  restart: always

mongo1:
  hostname: mongo1
  image: mongo:3.2
  entrypoint: [ "/usr/bin/mongod", "--replSet", "aem6", "--journal", "--smallfiles", "--rest" ]
  ports:
    - "27017:27017"
    - "28017:28017"
  links:
    - mongo2:mongo2
    - mongo3:mongo3
#  restart: always

# This configures the MongoDB replicaset
mongosetup:
  image: mongo:3.2
  links:
    - mongo1:mongo1
    - mongo2:mongo2
    - mongo3:mongo3
  volumes:
    - ./scripts:/scripts
  entrypoint: [ "/scripts/setup.sh" ]

aem61:
  hostname: aem
  build: aem/
  image: aem_aem61
  environment:
    - ENV CQ_JVM_OPTS="-server -Xmx1524M -Xms512M -XX:MaxPermSize=512M -mx4g -jar -r crx3,crx3mongo -Doak.mongo.uri=mongodb://mongo1:27017,mongo2:27017"
