java:
  build: java/
  container_name: java

aempub:
  hostname: aempub
  build: aem/
  dockerfile: Dockerfile-pub
  ports:
    - "4503:4503"
  command:
     ["java", "-XX:MaxPermSize=512M", "-Xmx1524M", "-Xms512M", "-jar", "cq-quickstart-6.1.0.jar", "-p", "4503", "-r", "publish"]
 #  restart: always

aemaut:
 hostname: aemaut
 build: aem/
 ports:
   - "4502:4502"
 links:
   - aempub:aempub
 command:
    ["java", "-XX:MaxPermSize=512M", "-Xmx1524M", "-Xms512M", "-jar", "cq-quickstart-6.1.0.jar", "-p", "4502", "-r", "author"]
#  restart: always

dispatcher:
 hostname: dispatcher
 build: dispatcher/
 ports:
   - "80:80"
   - "443:443"
 links:
   - aempub:aempub
# restart: always
